package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.TavernFighter;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TavernFighterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tavernfighter
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    int deleteByPrimaryKey(@Param("fighterid") Integer fighterid, @Param("tavernid") Integer tavernid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tavernfighter
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    int insert(TavernFighter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tavernfighter
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    List<TavernFighter> selectAll();

    List<TavernFighter> selectByFighterId(Integer fighterId);

    List<TavernFighter> selectByTavernId(Integer tavernId);
}