package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Tavern;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TavernsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taverns
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taverns
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    int insert(Tavern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taverns
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    Tavern selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taverns
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    List<Tavern> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.taverns
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    int updateByPrimaryKey(Tavern record);
}