package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Weapon;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface WeaponsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weapons
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weapons
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    int insert(Weapon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weapons
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    Weapon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weapons
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    List<Weapon> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.weapons
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    int updateByPrimaryKey(Weapon record);
}