package lt.vu.mybatis.model;

public class Fighter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fighters.id
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fighters.name
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fighters.power
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private Integer power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fighters.level
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fighters.phrase
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private String phrase;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fighters.id
     *
     * @return the value of public.fighters.id
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fighters.id
     *
     * @param id the value for public.fighters.id
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fighters.name
     *
     * @return the value of public.fighters.name
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fighters.name
     *
     * @param name the value for public.fighters.name
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fighters.power
     *
     * @return the value of public.fighters.power
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fighters.power
     *
     * @param power the value for public.fighters.power
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fighters.level
     *
     * @return the value of public.fighters.level
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fighters.level
     *
     * @param level the value for public.fighters.level
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fighters.phrase
     *
     * @return the value of public.fighters.phrase
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public String getPhrase() {
        return phrase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fighters.phrase
     *
     * @param phrase the value for public.fighters.phrase
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setPhrase(String phrase) {
        this.phrase = phrase;
    }
}