package lt.vu.mybatis.model;

public class Tavern {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taverns.id
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.taverns.name
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taverns.id
     *
     * @return the value of public.taverns.id
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taverns.id
     *
     * @param id the value for public.taverns.id
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.taverns.name
     *
     * @return the value of public.taverns.name
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.taverns.name
     *
     * @param name the value for public.taverns.name
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}