package lt.vu.mybatis.model;

public class TavernFighter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tavernfighter.fighterid
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private Integer fighterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tavernfighter.tavernid
     *
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    private Integer tavernid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tavernfighter.fighterid
     *
     * @return the value of public.tavernfighter.fighterid
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public Integer getFighterid() {
        return fighterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tavernfighter.fighterid
     *
     * @param fighterid the value for public.tavernfighter.fighterid
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setFighterid(Integer fighterid) {
        this.fighterid = fighterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tavernfighter.tavernid
     *
     * @return the value of public.tavernfighter.tavernid
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public Integer getTavernid() {
        return tavernid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tavernfighter.tavernid
     *
     * @param tavernid the value for public.tavernfighter.tavernid
     * @mbg.generated Mon Apr 13 23:13:50 EEST 2020
     */
    public void setTavernid(Integer tavernid) {
        this.tavernid = tavernid;
    }
}